name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ${{ vars.PROD_INSTANCE }}
    environment:
      name: "prod"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat > .env <<EOL
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }}
          S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          CAMPAIGN_PROCESSING_WEBHOOK_URL=${{ secrets.CAMPAIGN_PROCESSING_WEBHOOK_URL }}
          ENABLE_WEBHOOK_PROCESSING=${{ secrets.ENABLE_WEBHOOK_PROCESSING }}
          CONTAINER_PORT=${{ secrets.CONTAINER_PORT }}
          CONTAINER_NAME=${{ secrets.CONTAINER_NAME }}
          EOL

      - name: Stop and remove existing containers
        run: docker compose down --remove-orphans

      - name: Build and run Docker containers
        run: docker compose up --build -d --remove-orphans
